# -*- coding: utf-8 -*-
"""Classification Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTyU_SLvGoee0HbSvUdCygnSoDli3IlK
"""

# Code snippet 0
# Installing pycaret AI package for ML modeling
!pip install -U --pre pycaret

# Code snippet 1
# Importing the dataset
import pandas as pd
data = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSifbk44BcWITC1-_Q8O9Q0Vzs20FLIWZyTbbt9TjxI5nZUdLFYxO_wgy2J77fkVvzJ0lTVLvGn9GIP/pub?gid=0&single=true&output=csv')

# Displaying data shape
data.shape

# Code snippet 2
# Displaying column names
data.columns

# Code snippet 3
# Setting the target variable
y = 'BikeBuyer'

# Code snippet 4
# Importing missingno package to check missing data
import missingno as msno

# Displaying missing data
msno.bar(data)

ignored_cols = ['AveMonthSpend','CustomerID','Title', 'FirstName',
       'MiddleName', 'LastName', 'Suffix', 'AddressLine1', 'AddressLine2', 'PostalCode',
       'PhoneNumber']

# Code snippet 5
# Setting the numerical columns
num_cols = ['NumberCarsOwned',
       'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome']

# Code snippet 6
# Setting the categorical columns
cat_cols = ['City', 'StateProvinceName', 'CountryRegionName','Education', 'Occupation', 'Gender',
       'MaritalStatus', 'HomeOwnerFlag','BirthDate']

# Code snippet 7
# Importing classification modules from pycaret
from pycaret.classification import *

# Code snippet 8
# Setting/configuring pycaret ML modeling experiment
classification_model_setup = setup(data,
                               target = y,
                               ignore_features = ignored_cols,
                               numeric_features = num_cols,
                               categorical_features = cat_cols)

# Code snippet 9
# Invoking ML algorithms
compare_models()

# Code snippet 10
# Building the classification model with the best algo
classification_model = create_model('nb')

client_data = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTkZJ1CrmqZMztU1v7VShkyyP65Ujjhd4unSPyg6WDYd95DqRVyapFCyPI7TAKLtf4u6AJb7sn4pqJm/pub?gid=0&single=true&output=csv')

client_data_predictions = predict_model(classification_model, client_data)

client_data_predictions