# -*- coding: utf-8 -*-
"""Regression Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUQJ8uGLh5c9CKXCjfwiYkidrnZyYTgB
"""

# Code snippet 0
# Installing pycaret AI package for ML modeling
!pip install -U --pre pycaret

# Code snippet 1
# Installing pandas and numpy for numerical calulcations)
import pandas as pd
import numpy as np

# Code snippet 2
# Importing the dataset
data  = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSifbk44BcWITC1-_Q8O9Q0Vzs20FLIWZyTbbt9TjxI5nZUdLFYxO_wgy2J77fkVvzJ0lTVLvGn9GIP/pub?gid=0&single=true&output=csv')

# Displaying the data
data

# Importing missingno package to check missing data
import missingno as msno

# Displaying missing data
msno.bar(data)

# Code snippet 3
# Displaying column names
data.columns

# Code snippet 4
# Set ignored columns (noise/redundant variables/missing data variables)
ignored_cols = ['BikeBuyer','CustomerID','Title', 'FirstName',
       'MiddleName', 'LastName', 'Suffix', 'AddressLine1', 'AddressLine2', 'PostalCode',
       'PhoneNumber']

# Code snippet 5
# Setting the numerical columns
num_cols = ['NumberCarsOwned',
       'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome']

# Code snippet 6
# Setting the categorical columns
cat_cols = ['City', 'StateProvinceName', 'CountryRegionName','Education', 'Occupation', 'Gender',
       'MaritalStatus', 'HomeOwnerFlag','BirthDate']

# Code snippet 7
# Setting the target variable
y = 'AveMonthSpend'

# Code snippet 8
# Importing regression modules from pycaret
from pycaret.regression import *

# Code snippet 9
# Setting/configuring pycaret ML modeling experiment
regression_model_setup = setup(data,
                               target = y,
                               ignore_features = ignored_cols,
                               numeric_features = num_cols,
                               categorical_features = cat_cols)

# Code snippet 10
# Invoking ML algorithms
compare_models()

regression_model = create_model('et')

client_data = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTkZJ1CrmqZMztU1v7VShkyyP65Ujjhd4unSPyg6WDYd95DqRVyapFCyPI7TAKLtf4u6AJb7sn4pqJm/pub?gid=0&single=true&output=csv')

client_data_predictions = predict_model(regression_model, client_data)

client_data_predictions